name: Release

on: 
  push:
    branches:
      - master
  workflow_dispatch:

env:
  BUILD_SH: build.sh

jobs:
  Build:
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@master
      - name: 'Build'
        run: |
            curl -sL -H "Authorization: token ${{ secrets.TOKEN }}" -sL https://api.github.com/repos/wei2ard/pkgs-Settings/releases/latest | jq '.assets' | jq '.[0].url' | xargs -I {} curl -sL {} -H "Authorization: token ${{ secrets.TOKEN }}" -H 'Accept:application/octet-stream' -o pkgs-Settings.zip
            curl -sL -H "Authorization: token ${{ secrets.TOKEN }}" -sL https://api.github.com/repos/wei2ard/pkgs-R2Config/releases/latest | jq '.assets' | jq '.[0].url' | xargs -I {} curl -sL {} -H "Authorization: token ${{ secrets.TOKEN }}" -H 'Accept:application/octet-stream' -o pkgs-R2Config.zip
            curl -sL -H "Authorization: token ${{ secrets.TOKEN }}" -sL https://api.github.com/repos/wei2ard/pkgs-Guides/releases/latest | jq '.assets' | jq '.[0].url' | xargs -I {} curl -sL {} -H "Authorization: token ${{ secrets.TOKEN }}" -H 'Accept:application/octet-stream' -o pkgs-Guides.zip
            curl -sL -H "Authorization: token ${{ secrets.TOKEN }}" -sL https://api.github.com/repos/wei2ard/pkgs-Magic/releases/latest | jq '.assets' | jq '.[0].url' | xargs -I {} curl -sL {} -H "Authorization: token ${{ secrets.TOKEN }}" -H 'Accept:application/octet-stream' -o pkgs-Magic.zip
            curl -sL -H "Authorization: token ${{ secrets.TOKEN }}" -sL https://api.github.com/repos/wei2ard/ovls-Arcane/releases/latest | jq '.assets' | jq '.[0].url' | xargs -I {} curl -sL {} -H "Authorization: token ${{ secrets.TOKEN }}" -H 'Accept:application/octet-stream' -o ovls-Arcane.zip
            curl -sL -H "Authorization: token ${{ secrets.TOKEN }}" -sL https://api.github.com/repos/wei2ard/ovls-EdiZon/releases/latest | jq '.assets' | jq '.[0].url' | xargs -I {} curl -sL {} -H "Authorization: token ${{ secrets.TOKEN }}" -H 'Accept:application/octet-stream' -o ovls-EdiZon.zip
            curl -sL -H "Authorization: token ${{ secrets.TOKEN }}" -sL https://api.github.com/repos/wei2ard/ovls-FPSLocker/releases/latest | jq '.assets' | jq '.[0].url' | xargs -I {} curl -sL {} -H "Authorization: token ${{ secrets.TOKEN }}" -H 'Accept:application/octet-stream' -o ovls-FPSLocker.zip
            curl -sL -H "Authorization: token ${{ secrets.TOKEN }}" -sL https://api.github.com/repos/wei2ard/ovls-ReverseNX-RT/releases/latest | jq '.assets' | jq '.[0].url' | xargs -I {} curl -sL {} -H "Authorization: token ${{ secrets.TOKEN }}" -H 'Accept:application/octet-stream' -o ovls-ReverseNX-RT.zip
            curl -sL -H "Authorization: token ${{ secrets.TOKEN }}" -sL https://api.github.com/repos/wei2ard/ovls-Status-Monitor/releases/latest | jq '.assets' | jq '.[0].url' | xargs -I {} curl -sL {} -H "Authorization: token ${{ secrets.TOKEN }}" -H 'Accept:application/octet-stream' -o ovls-Status-Monitor.zip
            curl -sL -H "Authorization: token ${{ secrets.TOKEN }}" -sL https://api.github.com/repos/wei2ard/ovls-sys-clk-oc/releases/latest | jq '.assets' | jq '.[0].url' | xargs -I {} curl -sL {} -H "Authorization: token ${{ secrets.TOKEN }}" -H 'Accept:application/octet-stream' -o ovls-sys-clk-oc.zip
            curl -sL -H "Authorization: token ${{ secrets.TOKEN }}" -sL https://api.github.com/repos/wei2ard/nros-JKSV/releases/latest | jq '.assets' | jq '.[0].url' | xargs -I {} curl -sL {} -H "Authorization: token ${{ secrets.TOKEN }}" -H 'Accept:application/octet-stream' -o nros-JKSV.zip
            curl -sL -H "Authorization: token ${{ secrets.TOKEN }}" -sL https://api.github.com/repos/wei2ard/sys-sigpatches/releases/latest | jq '.assets' | jq '.[0].url' | xargs -I {} curl -sL {} -H "Authorization: token ${{ secrets.TOKEN }}" -H 'Accept:application/octet-stream' -o sys-sigpatches.zip

      - name: 'Release'
        uses: softprops/action-gh-release@master
        with:
          prerelease: false
          generate_release_notes: false
          tag_name: 'latest'
          files: |
            pkgs-Settings.zip
            pkgs-R2Config.zip
            pkgs-Guides.zip
            pkgs-Magic.zip
            ovls-Arcane.zip
            ovls-EdiZon.zip
            ovls-FPSLocker.zip
            ovls-ReverseNX-RT.zip
            ovls-Status-Monitor.zip
            ovls-sys-clk-oc.zip
            nros-JKSV.zip
            sys-sigpatches.zip
